# 1- Arrays

### Description

__Task__

- You are given a space separated list of numbers.
- Your task is to print a reversed NumPy array with the element type float.

__Input Format__

- A single line of input containing space separated numbers.

__Output Format__

- Print the reverse NumPy array with type float.

__Sample Input__

- 1 2 3 4 -8 -10

__Sample Output__

- [-10.  -8.   4.   3.   2.   1.]

### Solution

In [1]:
import numpy as np
def arrays(arr):
    re_arr = np.array(arr[::-1], float)
    return re_arr
arr = input().strip().split()
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# 2- Shape and Reshape

### Description

__Task__

- You are given a space separated list of nine integers. Your task is to convert this list into a __3 X 3__ NumPy array.

__Input Format__

- A single line of input containing __9__ space separated integers.

__Output Format__

- Print the __3 X 3__ NumPy array.

__Sample Input__

- 1 2 3 4 5 6 7 8 9

__Sample Output__

- [[1 2 3]
  [4 5 6]
  [7 8 9]]

# 3- Transpose and Flatten

### Description

__Task__

- You are given a __N X M__ integer array matrix with space separated elements (__N__ = rows and __M__ = columns).
- Your task is to print the transpose and flatten results.

__Input Format__

- The first line contains the space separated values of __N__ and __M__.
- The next __N__ lines contains the space separated elements of __M__ columns.

__Output Format__

- First, print the transpose array and then print the flatten.

__Sample Input__

- 2 2
- 1 2
- 3 4

__Sample Output__

- [[1 3]
  [2 4]]
  [1 2 3 4]

### Solution

In [6]:
import numpy as np
N, M = map(int, input().split())
arr = np.array([input().split() for n in range(N)], int)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# 4- Concatenate

### Description

__Task__

- You are given two integer arrays of size __N x P__ and __M x P__ (__N__ & __M__  are rows, and __P__ is the column). Your task is to concatenate the arrays along axis .

__Input Format__

- The first line contains space separated integers __N__, __M__ and __P__.
- The next __N__ lines contains the space separated elements of the __P__ columns.
- After that, the next __M__ lines contains the space separated elements of the __P__ columns.

__Output Format__

- Print the concatenated array of size __(N + M) x P__.

__Sample Input__

- 4 3 2
- 1 2
- 1 2 
- 1 2
- 1 2
- 3 4
- 3 4
- 3 4 

__Sample Output__

- [[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

### Solution

In [10]:
import numpy as np
N, M, P = map(int, input().split())
arr1 = np.array([input().split() for n in range(N)], int)
arr2 = np.array([input().split() for m in range(M)], int)
print(np.concatenate((arr1, arr2), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
